name: moto_events
description: "Route 22 app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 
  firebase_auth: 
  google_sign_in:
  app_settings: ^4.1.0
  path: ^1.8.0
  provider: 
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  permission_handler:
  flutter_map: 6.1.0
  flutter_map_location_marker: any
  firebase_storage: 
  location: ^5.0.3
  image_picker: ^1.0.7
  firebase_app_check: 
  collection: ^1.18.0
  map_launcher:
  cached_network_image: ^3.3.1
  flutter_web_browser: ^0.17.1
  connectivity_plus: ^2.0.2
  shared_preferences: ^2.0.13
  cupertino_icons:
  google_fonts: 6.1.0
  tab_indicator_styler: ^2.0.0
  carousel_slider: ^4.0.0
  confetti: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/routelogo.png 